export const getMestres = () => [
  'Josefhmw3',
  'Nightfb2017',
  'Odairgv',
  'Makiroto',
  'Anikilaki ',
  'SkaterReborn',
  'Legendsannin ',
  'kauezitto',
  'Luiskemily',
  'Miyagi_Ryota543',
  'WRover',
];

export const getLinks = () => [
  {
    title: "FACEBOOK Nioh & Soul's Brothers",
    url: 'https://www.facebook.com/groups/2540216682670198/',
  },
  {
    title: 'Canal YouTube  -  Bankai Build Moço',
    url: 'https://www.youtube.com/channel/UCclyF9EgcRc-MmTHugqNfXQ',
  },
  {
    title: "Grupo WhatsApp - Nioh & Soul's Brothers",
    url: 'https://chat.whatsapp.com/K7lLooE32ykBIc3YHdFaQe',
  },
];

export const getBuilds = () => [
  {
    props: {
      title: 'Espiritual Amaterasu',
      status: {
        corpo: 100,
        essencia: 100,
        forca: 100,
        energia: 22,
        habilidade: 170,
        destreza: 50,
        magia: 50,
        espirito: 200,
      },
      gracas: [
        {
          title: 'Graça de Amaterasu 5 peças',
          data: [
            'Redução de dano 3,2%',
            'Vida + 696',
            'Aumento de atace corpo a corpo 13,9%',
            'Efeito de ataque (Espírito) A',
          ],
        },
        {
          title: 'Graça de Sakuyahime 3 peças',
          data: ['Redução de dano 3,2%', 'Aumento do ataque (queimando) 22,1%'],
        },
        {
          title: 'Graça de Izanagi​ 4 peças',
          data: [
            'Redução de dano 3,2%',
            'Aumento do ataque (regeneração)',
            'combate corpo a corpo 13,8%',
          ],
        },
      ],
      armas: [
        {
          title: 'Katana',
          data: [
            'Bonus de danu por Familiaridade a+ (roleta)',
            'Dano de habilidade 21.9%',
            'Maestría Saque Rápido de Iai 24.7%',
            'perfurar defesa em combate corpo a corpo 13,9 (herança)',
            'Efeito de ataque Espírito a+ (Têmpera)',
          ],
        },
        {
          title: 'Lança',
          data: [
            'Bonus de danu por Familiaridade a+ (roleta)',
            'Dano de habilidade 21.9%',
            'Maestría Lança Giratória 26.7%',
            'perfurar defesa em combate corpo a corpo 13,9 (herança)',
            'Efeito de ataque Espírito A+ (Têmpera)',
            'Elemento (opicional)',
          ],
        },
        {
          title: 'Kusarigama',
          data: [
            'Bonus de danu por Familiaridade a+ (roleta)',
            'Maestria Mudar para ataque Habilidade AA (Forja)',
            'Elemento adicional',
            'Perfurar defesa em combate corpo a corpo 13,9 (herança)',
            'Dano de combate corpo a corpo 20%',
          ],
        },
        {
          title: 'Armas de Longo Alcance',
          data: [
            'Bonus de dano de Agilidade A+',
            'Redução da velocidade de mira',
            'Rastreio automático',
            'Dano de Dano de arma de longo alcance',
          ],
        },
      ],
      protecao: [
        {
          title: 'Kabuto',
          data: [
            'Bonus por absorver amrita Aumento do ataque',
            'Maestría Aumento de ataque inimigo sem Ki',
            'Redução de peso',
            'Redução de dano elemental enquanto defende',
            'Ataque (Herança)',
          ],
        },
        {
          title: 'Peitoral',
          data: [
            'Bonus ao ser cercado aumento do ataque',
            'Redução de dano elemental enquanto defende (Herança)',
            'Bonus de ki zero aumento do ataque',
            'Tenacidade bonus contínuo',
            'Redução de peso',
          ],
        },
        {
          title: 'Luva',
          data: [
            'Aumento de ataque corpo a corpo',
            'Redução de dano elemental enquanto defende (Herança)',
            'Aumento de ataque defesa pontual',
            'Aumentar ataque e defesa Kato',
            'Ataque',
          ],
        },
        {
          title: 'Calça',
          data: [
            'Bônus por efeito adverso sofrido aumento do ataque',
            'Aumento da velocidade de marcha ou  Redução de peso',
            'Ataque (Herança)',
            'Diminuir Tempo de Recuperação (Ki Esgotado)',
            'Maestria Aumento do ataque após usar arma viva',
          ],
        },
        {
          title: 'Bota',
          data: [
            'Redução de peso',
            'Bônus por purificação aumento do ataque',
            'Aumento da velocidade de marcha',
            'Ataque (Herança)',
            'Maestría Aumento de ataque crítico',
          ],
        },
        {
          title: 'Yasakani Magatama',
          data: [
            'Dano de combate corpo a corpo em yokay 10.8%',
            'Aumento de ataque de armas vivas 12,4%',
            'Os demais data são opcionais',
          ],
        },
        {
          title: 'Magatama',
          data: [
            'Dano de combate corpo a corpo em yokay 10.8%',
            'Aumento de ataque de armas vivas 12,4%',
            'Os demais data são opcionais',
          ],
        },
      ],
      itensAtalho: [
        'Elixir',
        'Talismã da preguiça',
        'Talismã da fragilidade',
        'Talismã da carnificina',
        'Talismã do kekai',
        'Talismã da extração',
        'Talismã das pleiades',
        'Talismã Sanguessuga',
        'Pergaminho tigre corredor',
        'Pergaminho de troca rapida',
        'Talismã do momento',
        'Talimsa do eremita',
        'Pedra espiritual',
        'Jarro de oleo flamejante',
        'Vaso de agua dos yoais',
        'Talismã da regeneração',
      ],
      guardioes: [
        {
          title: 'Enku',
          data: [
            'proteção espiritual 26%',
            'Negar dano (ataque em corrida)',
            'Aumento da velocidade de corrida 10%',
            'Dano (Efeitos adversos) B-',
            'Dano de estocada +14%',
            'Ataque de combate corpo a corpo (Inimigo Atacando)',
          ],
        },
        {
          title: 'Aya-Komori (Secundário)',

          data: ['Ataque pelas costas + 9%', 'Proteção do Timbre'],
        },
      ],
      cla: {
        title: 'Clã Utsunomiya',
        observacao:
          'Esse clã dá um surto de dano após purificar, o que dá a oportunidade de um ataque com muito dano em poucos segundos',
        opcional:
          '(opcional ranquear no clã para aumentar o efeito de ataque espírito de D para A)',
      },
      habilidades: [
        {
          title: 'Katana',
          data: [
            'Agarrar: Chute',
            'Espírito indomável (passiva)',
            'Purificar reino dos yokais (passiva)',
            'Fluxo 1 e 2',
            'Lampejo',
            'Saque Rápido Iai 1 2 e 3',
            'Chuva noturna',
            'Ki da espada',
            'Implacável (passiva)',
            'Golpe cruzado',
            'Espada do discernimento',
            'Luz da manhã',
            'Espada da execução (Arkanum)',
            'Asas de Andorinha 1 e 2',
            'Espada da meditação',
            'Pulso de ki divino',
            'Lua matinal',
            'Sombra fugaz',
            'Queda izuna ( habilidade especial dropada pelo Hayabusa - DLC)',
            'Agua viva',
            'Pulso de Ki: humano',
            "Sombra d'agua 1 e 2",
            'Agua viva : humano',
            'Folha ao vento',
            'Neblina 1 e 2',
            'Tempestade',
            'Contra onda 1 e 2',
            'Pulso de Ki : terreno',
            'Ráio celestial',
            'Água viva : terreno',
          ],
        },
        {
          title: 'Katana dupla',
          data: [
            'Purificar reino dos yokais (passiva)',
            'Arte da tachi (passiva)',
            'Arte defensiva (passiva)',
          ],
        },
        {
          title: 'Lança',
          data: [
            'Agarrar',
            'Chute pivotante',
            'Tigre encurralado (passiva)',
            'Purificar reino dos yokais (passiva)',
            'Fluxo 1 e 2',
            'Lampejo',
            'Empurrão com a lança',
            'Chidori',
            'Lança celestial',
            'Tornado',
            'Dragão ascendente',
            'Investida impiedosa',
            'Pulso de ki : divino',
            'Chva perfurante',
            'Regra n. 3 da estocada (passiva)',
            'Água viva: divinoLança descendente',
            'Estabilidade (​ Arkanum​ )',
            'Mudança da postura com Lança',
            'Moinho 1 e 2',
            'Pulso de Ki: Humano',
            'Troca de corpos',
            "Roda D'Água",
            'Água viva: humano',
            'Rodopio 1 e 2',
            'Lança giratória',
            'Lanaça selvagem',
            'Emaranhado',
            'Pulso de Ki: terreno',
            'Contrapé',
            'Batida de lança',
            'Água viva: Terreno',
            'Macaco voador 1 e 2',
          ],
        },
        {
          title: 'Machado',
          data: [
            'Constituição (passiva)',
            'Purificar reino dos yokais',
            'Javali Encurralado',
          ],
        },
        {
          title: 'Kusarigama',
          data: [
            'Agarrar',
            'Ceifador',
            'Noite de verão',
            'Chute redemoinho',
            'Golpe em salto',
            'Lâmina giratória',
            'Purificar reino dos yokais (passiva)',
            'Fluxo 1 e 2',
            'Lampejo',
            'Pulso de ki divino',
            'Rasteira',
            'Perfuração (passiva)',
            'Corte Crescente (​ Arckanum​ )',
            'Água viva: divino',
            'Golpe da serpente',
            'Turbilhão escarlate 1 e 2',
            'Pulso de ki: Humano',
            "Queda D'Água",
            'Água viva: humana',
            'ponto cego (passiva)',
            'Redemoinho',
            'Libertação',
            'Dragão renegado',
            'Ataque imobilizador 1 e 2',
            'Pulso de ki: terreno',
            'Recuar atacando',
            'Kata da lua cheia (passiva)',
            'Água viva: terreno',
          ],
        },
        {
          title: 'Odachi',
          data: ['Purificar reino dos yokai', 'Passagem ao além (passiva)'],
        },
        {
          title: 'Tonfa',
          data: [
            'Flutuação (passiva)',
            'Mestre em combate corpo a corpo (​ upar o máximo possível​ )',
          ],
        },
        {
          title: 'Ninjutsu',
          data: [
            'Mestre das ferramentas ninja (passiva)',
            'Resiliência (passiva)',
            'Técnica da mordida da serpente (passiva)',
            'Curandeiro (passiva)',
            'Ataque furtivo',
            'Esquiva (passiva)',
            'Pé de vento (passiva)',
            'Corrida (passiva)',
            'Mestre do canhão (passiva)',
            'Mestre do fecho de mecha (passiva)',
            'Mestre do arco (passiva)',
            'Controle de veneno (passiva)',
            'Controle de paralisia (passiva)',
          ],
        },
        {
          title: 'Magia Omio',
          data: [
            'Corta fogo (passiva)',
            "À prova D'água (passiva)",
            'Quebra vento (passiva)',
            'Isolamento elétrico (passiva)',
            'Paraterra (passiva) aprender só 1 nível',
            'Mente sã (passiva)',
            'Céu puro, Terra amaldiçoada (passiva)',
            'Água milagrosa (passiva)',
            'Cura rápida da Panaceia (passiva)',
            'Proteção contra o mal (passiva)',
            'Encantamento de inanimados (passiva)',
            'Mestre do encantamento (passiva)',
          ],
        },
      ],
    },
  },
];
